In [1]:
# Random Forest models
%run 07_model_functions.py

import json
import os
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)

In [2]:
# Low policy: face-mask outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "low_face_mask_train.csv",
    "low_face_mask_test.csv",
    "face_mask_behaviour_binary"
)

rf_low_face_mask_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_low_face_mask_result = {
    "best_cv_auc": rf_low_face_mask_study.best_value,
    "best_params": rf_low_face_mask_study.best_params
}
with open(
    "../Model/rf_low_policy_face_mask_params.json", "w"
) as file:
    json.dump(rf_low_face_mask_result, file, indent=2)

rf_low_face_mask = fit_random_forest(
    X_train,
    y_train,
    rf_low_face_mask_study.best_params,
    n_estimators=500
)
rf_low_face_mask_metrics = evaluate_binary_model(
    rf_low_face_mask, X_test, y_test
)

rf_low_face_mask_importance = repeated_feature_importance(
    rf_low_face_mask, X_train, y_train, n_repeats=100
)
rf_low_face_mask_importance.to_csv(
    "../Importance/rf_low_policy_face_mask_importance.csv",
    index=False
)

display(rf_low_face_mask_metrics)
display(rf_low_face_mask_importance.head(10))

accuracy     0.875354
precision    0.889734
recall       0.939759
f1           0.914062
auc          0.938755
dtype: float64

                    feature  median_importance        q1        q3       iqr
6               week_number           0.340408  0.333245  0.345952  0.012707
9             H_policy_mean           0.205336  0.199091  0.211182  0.012091
7             C_policy_mean           0.147472  0.143646  0.150446  0.006801
1                       age           0.049312  0.048664  0.049941  0.001278
0                 i2_health           0.046919  0.046339  0.047368  0.001030
4                      r1_1           0.040083  0.039637  0.040702  0.001065
5                      r1_2           0.036101  0.035205  0.037065  0.001860
16  i11_health_Very willing           0.027899  0.027414  0.028249  0.000835
3            cantril_ladder           0.017369  0.017022  0.017729  0.000707
2            household_size           0.016242  0.015889  0.016602  0.000713

In [3]:
# Low policy: protective-behaviour outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "low_protective_train.csv",
    "low_protective_test.csv",
    "protective_behaviour_binary"
)

rf_low_protective_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_low_protective_result = {
    "best_cv_auc": rf_low_protective_study.best_value,
    "best_params": rf_low_protective_study.best_params
}
with open(
    "../Model/rf_low_policy_protective_params.json", "w"
) as file:
    json.dump(rf_low_protective_result, file, indent=2)

rf_low_protective = fit_random_forest(
    X_train,
    y_train,
    rf_low_protective_study.best_params,
    n_estimators=500
)
rf_low_protective_metrics = evaluate_binary_model(
    rf_low_protective, X_test, y_test
)

rf_low_protective_importance = repeated_feature_importance(
    rf_low_protective, X_train, y_train, n_repeats=100
)
rf_low_protective_importance.to_csv(
    "../Importance/rf_low_policy_protective_importance.csv",
    index=False
)

display(rf_low_protective_metrics)
display(rf_low_protective_importance.head(10))

accuracy     0.773371
precision    0.780328
recall       0.948207
f1           0.856115
auc          0.833529
dtype: float64

                    feature  median_importance        q1        q3       iqr
0                 i2_health           0.156664  0.154973  0.158108  0.003135
4                      r1_1           0.123178  0.121841  0.124792  0.002951
6               week_number           0.114099  0.112326  0.115955  0.003629
7             C_policy_mean           0.082004  0.080827  0.083652  0.002825
1                       age           0.078675  0.077429  0.079202  0.001773
9             H_policy_mean           0.078414  0.076723  0.080028  0.003304
16  i11_health_Very willing           0.051687  0.050436  0.052752  0.002316
5                      r1_2           0.050598  0.049809  0.051531  0.001721
3            cantril_ladder           0.042826  0.042044  0.043405  0.001360
2            household_size           0.035081  0.034537  0.035612  0.001075

In [4]:
# Medium policy: face-mask outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "medium_face_mask_train.csv",
    "medium_face_mask_test.csv",
    "face_mask_behaviour_binary"
)

rf_medium_face_mask_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_medium_face_mask_result = {
    "best_cv_auc": rf_medium_face_mask_study.best_value,
    "best_params": rf_medium_face_mask_study.best_params
}
with open(
    "../Model/rf_medium_policy_face_mask_params.json", "w"
) as file:
    json.dump(rf_medium_face_mask_result, file, indent=2)

rf_medium_face_mask = fit_random_forest(
    X_train,
    y_train,
    rf_medium_face_mask_study.best_params,
    n_estimators=500
)
rf_medium_face_mask_metrics = evaluate_binary_model(
    rf_medium_face_mask, X_test, y_test
)

rf_medium_face_mask_importance = repeated_feature_importance(
    rf_medium_face_mask, X_train, y_train, n_repeats=100
)
rf_medium_face_mask_importance.to_csv(
    "../Importance/rf_medium_policy_face_mask_importance.csv",
    index=False
)

display(rf_medium_face_mask_metrics)
display(rf_medium_face_mask_importance.head(10))

accuracy     0.819708
precision    0.836455
recall       0.813025
f1           0.824574
auc          0.892147
dtype: float64

          feature  median_importance        q1        q3       iqr
9   H_policy_mean           0.249787  0.246431  0.252778  0.006347
6     week_number           0.201869  0.199142  0.204475  0.005333
1             age           0.083751  0.083546  0.084031  0.000485
7   C_policy_mean           0.077609  0.076488  0.078626  0.002138
0       i2_health           0.060051  0.059864  0.060257  0.000394
4            r1_1           0.049654  0.049486  0.049824  0.000338
3  cantril_ladder           0.042264  0.042115  0.042470  0.000354
5            r1_2           0.040052  0.039627  0.040472  0.000845
8   E_policy_mean           0.035711  0.035348  0.036097  0.000749
2  household_size           0.029449  0.029336  0.029576  0.000240

In [5]:
# Medium policy: protective-behaviour outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "medium_protective_train.csv",
    "medium_protective_test.csv",
    "protective_behaviour_binary"
)

rf_medium_protective_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_medium_protective_result = {
    "best_cv_auc": rf_medium_protective_study.best_value,
    "best_params": rf_medium_protective_study.best_params
}
with open(
    "../Model/rf_medium_policy_protective_params.json", "w"
) as file:
    json.dump(rf_medium_protective_result, file, indent=2)

rf_medium_protective = fit_random_forest(
    X_train,
    y_train,
    rf_medium_protective_study.best_params,
    n_estimators=500
)
rf_medium_protective_metrics = evaluate_binary_model(
    rf_medium_protective, X_test, y_test
)

rf_medium_protective_importance = repeated_feature_importance(
    rf_medium_protective, X_train, y_train, n_repeats=100
)
rf_medium_protective_importance.to_csv(
    "../Importance/rf_medium_policy_protective_importance.csv",
    index=False
)

display(rf_medium_protective_metrics)
display(rf_medium_protective_importance.head(10))

accuracy     0.729927
precision    0.753586
recall       0.850289
f1           0.799022
auc          0.779839
dtype: float64

          feature  median_importance        q1        q3       iqr
0       i2_health           0.132930  0.132654  0.133191  0.000538
4            r1_1           0.108549  0.108218  0.108823  0.000605
1             age           0.101659  0.101426  0.101892  0.000466
6     week_number           0.100140  0.099611  0.100627  0.001016
9   H_policy_mean           0.078256  0.077886  0.078597  0.000711
7   C_policy_mean           0.060311  0.060136  0.060619  0.000483
3  cantril_ladder           0.059207  0.059024  0.059391  0.000367
5            r1_2           0.058160  0.057931  0.058380  0.000449
2  household_size           0.046901  0.046740  0.047051  0.000311
8   E_policy_mean           0.024406  0.024291  0.024565  0.000274

In [6]:
# High policy: face-mask outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "high_face_mask_train.csv",
    "high_face_mask_test.csv",
    "face_mask_behaviour_binary"
)

rf_high_face_mask_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_high_face_mask_result = {
    "best_cv_auc": rf_high_face_mask_study.best_value,
    "best_params": rf_high_face_mask_study.best_params
}
with open(
    "../Model/rf_high_policy_face_mask_params.json", "w"
) as file:
    json.dump(rf_high_face_mask_result, file, indent=2)

rf_high_face_mask = fit_random_forest(
    X_train,
    y_train,
    rf_high_face_mask_study.best_params,
    n_estimators=500
)
rf_high_face_mask_metrics = evaluate_binary_model(
    rf_high_face_mask, X_test, y_test
)

rf_high_face_mask_importance = repeated_feature_importance(
    rf_high_face_mask, X_train, y_train, n_repeats=100
)
rf_high_face_mask_importance.to_csv(
    "../Importance/rf_high_policy_face_mask_importance.csv",
    index=False
)

display(rf_high_face_mask_metrics)
display(rf_high_face_mask_importance.head(10))

accuracy     0.827545
precision    0.842168
recall       0.819710
f1           0.830787
auc          0.885650
dtype: float64

          feature  median_importance        q1        q3       iqr
9   H_policy_mean           0.261499  0.258347  0.264488  0.006142
7   C_policy_mean           0.159660  0.158280  0.161587  0.003307
6     week_number           0.157767  0.155316  0.159706  0.004390
1             age           0.079379  0.079194  0.079572  0.000379
0       i2_health           0.058250  0.058070  0.058447  0.000377
4            r1_1           0.044399  0.044234  0.044591  0.000357
3  cantril_ladder           0.040918  0.040756  0.041079  0.000323
5            r1_2           0.035972  0.035803  0.036128  0.000326
2  household_size           0.027573  0.027495  0.027696  0.000201
8   E_policy_mean           0.018114  0.017370  0.018818  0.001448

In [7]:
# High policy: protective-behaviour outcome
X_train, y_train, X_test, y_test = load_train_test_data(
    "high_protective_train.csv",
    "high_protective_test.csv",
    "protective_behaviour_binary"
)

rf_high_protective_study = tune_random_forest(
    X_train, y_train, n_estimators=500, n_trials=200
)

rf_high_protective_result = {
    "best_cv_auc": rf_high_protective_study.best_value,
    "best_params": rf_high_protective_study.best_params
}
with open(
    "../Model/rf_high_policy_protective_params.json", "w"
) as file:
    json.dump(rf_high_protective_result, file, indent=2)

rf_high_protective = fit_random_forest(
    X_train,
    y_train,
    rf_high_protective_study.best_params,
    n_estimators=500
)
rf_high_protective_metrics = evaluate_binary_model(
    rf_high_protective, X_test, y_test
)

rf_high_protective_importance = repeated_feature_importance(
    rf_high_protective, X_train, y_train, n_repeats=100
)
rf_high_protective_importance.to_csv(
    "../Importance/rf_high_policy_protective_importance.csv",
    index=False
)

display(rf_high_protective_metrics)
display(rf_high_protective_importance.head(10))

accuracy     0.772754
precision    0.793439
recall       0.887228
f1           0.837716
auc          0.846437
dtype: float64

          feature  median_importance        q1        q3       iqr
7   C_policy_mean           0.141631  0.140473  0.142799  0.002326
0       i2_health           0.136798  0.136214  0.137291  0.001076
1             age           0.087749  0.087522  0.087949  0.000427
9   H_policy_mean           0.087335  0.086631  0.088205  0.001574
6     week_number           0.085082  0.084573  0.085500  0.000927
4            r1_1           0.076580  0.076353  0.076886  0.000533
3  cantril_ladder           0.055384  0.055261  0.055578  0.000318
5            r1_2           0.048563  0.048417  0.048733  0.000317
2  household_size           0.043388  0.043247  0.043591  0.000344
8   E_policy_mean           0.022021  0.021732  0.022296  0.000564